"""SVG comparisons for calibrated back-paw to front-paw distance.

The workbook's wide frame sheet is deliberately human-friendly: every cell
contains the distance and the matching back-paw position.  This module reads
that sheet, converts valid frames into 10 cm beam bins, and gives every mouse
equal weight in group statistics.  It never fabricates observations across
missing or low-confidence frame gaps.
"""

from __future__ import annotations

from collections import defaultdict
from dataclasses import dataclass
import html
import math
from pathlib import Path
import re
import statistics
from typing import Iterable

from .condition_map import ConditionMapStore
from .dataset import ROOT, natural_day_key


OUTPUT_ROOT = ROOT / "outputs"
RESULTS_FILENAME = "RBT_CV_Results.xlsx"
SHEET_NAME = "Back-Front Paw Distance"
CHART_DIRECTORY = "Back_Front paw Distance"
FILE_SUFFIX = ".svg"
GROUP_PREFIX = "back_front_paw_distance_group_comparison_"
# Kept as cleanup identifiers for charts generated by earlier releases.  New
# refreshes do not create trial-to-trial consistency charts.
CONSISTENCY_PREFIX = "back_front_paw_distance_trial_consistency_"
WITHIN_TRIAL_VARIATION_PREFIX = "back_front_paw_distance_within_trial_variation_"
DAY_GROUP_FILENAME = "Day_back_front_paw_distance_group_comparison.svg"
DAY_CONSISTENCY_FILENAME = "Day_back_front_paw_distance_trial_consistency.svg"
DAY_WITHIN_TRIAL_VARIATION_FILENAME = "Day_back_front_paw_distance_within_trial_variation.svg"
BIN_STARTS_CM = tuple(range(0, 90, 10))

SHAM_COLOR = "#1976D2"
STROKE_COLOR = "#D32F2F"
UNASSIGNED_COLOR = "#616161"
ERROR_RANGE_COLOR = "#6B7280"
ERROR_WHISKER_COLOR = "#374151"
FRAME_CELL_RE = re.compile(r"([+-]?\d+(?:\.\d+)?) cm; ([+-]?\d+(?:\.\d+)?) cm")


@dataclass(frozen=True)
class TrialPawDistanceSeries:
    """One trial's mean stance distance within every 10 cm beam bin."""

    day: str
    cage: str
    animal: str
    condition: str
    trial: int
    bin_means: tuple[float | None, ...]
    # Raw valid frame distances are retained for position-controlled
    # within-trial variation.  They are grouped by the same 0--10 through
    # 80--90 cm back-paw bins as ``bin_means``.
    frame_distances_by_bin: tuple[tuple[float, ...], ...] = ()


@dataclass(frozen=True)
class MousePawDistanceSeries:
    """One mouse's trial-averaged stance distance within each beam bin."""

    day: str
    cage: str
    animal: str
    condition: str
    bin_means: tuple[float | None, ...]


@dataclass(frozen=True)
class GroupPawDistanceSummary:
    """Equal-mouse group mean and sample SD for every beam bin."""

    condition: str
    means: tuple[float | None, ...]
    standard_deviations: tuple[float | None, ...]
    mouse_counts: tuple[int, ...]


@dataclass(frozen=True)
class MousePawDistanceConsistency:
    """Within-mouse sample SD across trials for every beam bin."""

    day: str
    cage: str
    animal: str
    condition: str
    standard_deviations: tuple[float | None, ...]
    trial_counts: tuple[int, ...]


@dataclass(frozen=True)
class TrialPawDistanceWithinTrialVariation:
    """One trial's raw frame-to-frame distance variation in every beam bin."""

    day: str
    cage: str
    animal: str
    condition: str
    trial: int
    standard_deviations: tuple[float | None, ...]
    frame_counts: tuple[int, ...]


@dataclass(frozen=True)
class DayGroupPawDistanceSummary:
    """One equal-mouse group summary for each experimental day."""

    condition: str
    means: dict[str, float]
    standard_deviations: dict[str, float | None]
    mouse_counts: dict[str, int]


class BackFrontPawDistancePlotStore:
    """Create group and within-trial-variation charts from the frame-distance sheet."""

    def __init__(self, output_root: Path = OUTPUT_ROOT) -> None:
        self.output_root = output_root

    def result_dir(self, dataset: str) -> Path:
        return self.output_root / f"{dataset} Results"

    def chart_dir(self, dataset: str) -> Path:
        return self.result_dir(dataset) / CHART_DIRECTORY

    def refresh_dataset(self, dataset: str) -> dict[str, Path]:
        """Regenerate all back/front-paw distance charts for one dataset."""
        workbook_path = self.result_dir(dataset) / RESULTS_FILENAME
        if not workbook_path.exists():
            return {}

        conditions = ConditionMapStore(self.output_root).load(dataset)
        trials = self._read_trial_series(workbook_path, conditions)
        by_day: dict[str, list[TrialPawDistanceSeries]] = defaultdict(list)
        for series in trials:
            by_day[series.day].append(series)

        chart_dir = self.chart_dir(dataset)
        chart_dir.mkdir(parents=True, exist_ok=True)
        paths: dict[str, Path] = {}
        for day, day_trials in sorted(by_day.items(), key=lambda item: natural_day_key(item[0])):
            mice, groups = summarize_group_back_front_paw_distances(day_trials)
            group_path = chart_dir / f"{GROUP_PREFIX}{day}{FILE_SUFFIX}"
            self._write_svg(
                group_path,
                self._daily_group_svg(dataset, day, day_trials, mice, groups),
            )
            paths[f"group:{day}"] = group_path

            variation_trials, variation_mice, variation_groups = (
                summarize_back_front_paw_distance_within_trial_variation(day_trials)
            )
            variation_path = chart_dir / f"{WITHIN_TRIAL_VARIATION_PREFIX}{day}{FILE_SUFFIX}"
            self._write_svg(
                variation_path,
                self._daily_within_trial_variation_svg(
                    dataset,
                    day,
                    variation_trials,
                    variation_mice,
                    variation_groups,
                ),
            )
            paths[f"within_trial_variation:{day}"] = variation_path

        day_group_path = chart_dir / DAY_GROUP_FILENAME
        self._write_svg(
            day_group_path,
            self._day_bar_svg(
                dataset,
                summarize_day_by_day_back_front_paw_distances(trials),
                title="Day-by-day back/front paw-distance comparison",
                calculation_note=(
                    "For each day, each mouse is averaged across its trials and valid "
                    "10 cm bins from 0-90 cm before group calculation."
                ),
                comparison_note=(
                    "Colored bars are SHAM/STROKE mean distances; neutral-gray ranges and "
                    "whiskers are plus/minus 1 sample SD across mice."
                ),
                empty_note="No SHAM or STROKE back/front paw-distance data are available yet.",
                y_label="Back-paw to front-paw distance (cm)",
            ),
        )
        paths["day_group"] = day_group_path

        day_variation_path = chart_dir / DAY_WITHIN_TRIAL_VARIATION_FILENAME
        self._write_svg(
            day_variation_path,
            self._day_bar_svg(
                dataset,
                summarize_day_by_day_back_front_paw_distance_within_trial_variation(trials),
                title="Day-by-day back/front paw-distance within-trial variation",
                calculation_note=(
                    "For each 10 cm bin, calculate each trial's sample SD across raw valid "
                    "frames; each mouse contributes the mean of its trial/bin SDs."
                ),
                comparison_note=(
                    "Colored bars are SHAM/STROKE means; neutral-gray ranges and whiskers "
                    "are plus/minus 1 sample SD across mice. Lower SD means more consistent posture and gait."
                ),
                empty_note="No SHAM or STROKE back/front paw-distance variation data are available yet.",
                y_label="Within-trial paw-distance SD (cm; lower = more consistent)",
            ),
        )
        paths["day_within_trial_variation"] = day_variation_path

        live_names = {path.name for path in paths.values()}
        for prefix in (GROUP_PREFIX, WITHIN_TRIAL_VARIATION_PREFIX):
            for stale_path in chart_dir.glob(f"{prefix}*{FILE_SUFFIX}"):
                if stale_path.name not in live_names:
                    stale_path.unlink()
        # Only remove the known legacy trial-to-trial consistency artifacts;
        # no user-created files in the chart directory are touched.
        for stale_path in chart_dir.glob(f"{CONSISTENCY_PREFIX}*{FILE_SUFFIX}"):
            stale_path.unlink()
        obsolete_day_consistency = chart_dir / DAY_CONSISTENCY_FILENAME
        if obsolete_day_consistency.exists():
            obsolete_day_consistency.unlink()
        return paths

    @staticmethod
    def _read_trial_series(
        workbook_path: Path,
        conditions: dict[tuple[str, str], str],
    ) -> list[TrialPawDistanceSeries]:
        from openpyxl import load_workbook

        workbook = load_workbook(workbook_path, data_only=True, read_only=True)
        try:
            if SHEET_NAME not in workbook.sheetnames:
                return []
            sheet = workbook[SHEET_NAME]
            headers = [cell.value for cell in next(sheet.iter_rows(max_row=1), ())]
            index = {
                str(header): position
                for position, header in enumerate(headers)
                if header is not None
            }
            required = ("Day", "Cage", "Animal", "Trial")
            if not all(header in index for header in required):
                return []
            compact, separate_distances, separate_positions = _frame_columns(index)

            output: list[TrialPawDistanceSeries] = []
            for values in sheet.iter_rows(min_row=2, values_only=True):
                day = _cell_text(values, index["Day"])
                cage = _cell_text(values, index["Cage"])
                animal = _cell_text(values, index["Animal"])
                trial = _cell_int(values, index["Trial"])
                if not (day and cage and animal and trial):
                    continue

                by_bin: dict[int, list[float]] = defaultdict(list)
                for frame in set(compact) | set(separate_distances) | set(separate_positions):
                    distance, position = _frame_measurement(
                        values,
                        frame,
                        compact,
                        separate_distances,
                        separate_positions,
                    )
                    if distance is None or position is None:
                        continue
                    bin_start = _bin_start(position)
                    if bin_start is not None:
                        by_bin[bin_start].append(distance)
                if not by_bin:
                    continue
                output.append(
                    TrialPawDistanceSeries(
                        day=day,
                        cage=cage,
                        animal=animal,
                        condition=conditions.get((cage, animal), "UNASSIGNED"),
                        trial=trial,
                        bin_means=tuple(
                            statistics.fmean(by_bin[start]) if by_bin[start] else None
                            for start in BIN_STARTS_CM
                        ),
                        frame_distances_by_bin=tuple(
                            tuple(by_bin[start]) for start in BIN_STARTS_CM
                        ),
                    )
                )
            return output
        finally:
            workbook.close()

    @staticmethod
    def _write_svg(path: Path, text: str) -> None:
        temporary_path = path.with_suffix(f"{path.suffix}.tmp")
        try:
            temporary_path.write_text(text, encoding="utf-8")
            temporary_path.replace(path)
        finally:
            if temporary_path.exists():
                temporary_path.unlink()

    @staticmethod
    def _daily_group_svg(
        dataset: str,
        day: str,
        trial_series: Iterable[TrialPawDistanceSeries],
        mouse_series: Iterable[MousePawDistanceSeries],
        group_summaries: Iterable[GroupPawDistanceSummary],
    ) -> str:
        trials = sorted(trial_series, key=_trial_sort_key)
        groups = sorted(group_summaries, key=lambda item: _condition_order(item.condition))
        values = _all_bin_values(trials)
        values.extend(_summary_edges(groups))
        lower, upper = _zoomed_nonnegative_axis_bounds(values)
        width, height = 1420, 790
        left, right, top, bottom = 96, 390, 94, 150
        chart_width, chart_height = width - left - right, height - top - bottom
        x = _bin_x(left, chart_width)
        y = _value_y(top, chart_height, lower, upper)

        parts = _svg_header(
            width,
            height,
            left,
            f"Back/front paw-distance group comparison - {dataset} {day}",
            "Thin lines are trial means within each 10 cm bin. Each mouse is averaged across its trials before it enters the group mean, so every mouse has equal weight.",
            "Thick lines are group means; shaded bands are plus/minus 1 sample SD across mouse means. Gaps indicate no valid observations.",
        )
        _append_bin_axes(
            parts,
            left,
            top,
            chart_width,
            chart_height,
            x,
            y,
            lower,
            upper,
            "Back-paw to front-paw distance (cm)",
            height,
        )
        _append_summary_bands(parts, groups, x, y, lower, upper)
        for series in trials:
            color = _condition_color(series.condition)
            tooltip = html.escape(
                f"{series.condition.title()} | Cage {series.cage} Mouse {series.animal} | Trial T{series.trial}"
            )
            _append_hover_lines(
                parts,
                _line_segments(series.bin_means, x, y),
                color,
                tooltip,
                1.7,
                0.28,
            )
        _append_summary_lines(parts, groups, x, y)
        _append_group_legend(parts, groups, left + chart_width + 40, top)
        parts.append("</svg>")
        return "\n".join(parts)

    @staticmethod
    def _daily_consistency_svg(
        dataset: str,
        day: str,
        mouse_series: Iterable[MousePawDistanceConsistency],
        group_summaries: Iterable[GroupPawDistanceSummary],
    ) -> str:
        mice = sorted(
            mouse_series,
            key=lambda item: (
                _condition_order(item.condition),
                _numeric_key(item.cage),
                _numeric_key(item.animal),
            ),
        )
        groups = sorted(group_summaries, key=lambda item: _condition_order(item.condition))
        values = [
            value
            for mouse in mice
            for value in mouse.standard_deviations
            if _valid(value)
        ]
        values.extend(_summary_edges(groups))
        lower, upper = _zoomed_nonnegative_axis_bounds(values)
        width, height = 1420, 790
        left, right, top, bottom = 96, 390, 94, 150
        chart_width, chart_height = width - left - right, height - top - bottom
        x = _bin_x(left, chart_width)
        y = _value_y(top, chart_height, lower, upper)

        parts = _svg_header(
            width,
            height,
            left,
            f"Back/front paw-distance trial consistency - {dataset} {day}",
            "Thin lines show each mouse's sample SD across valid trials in each 10 cm bin. Higher SD means greater trial-to-trial variation.",
            "Thick lines are group means; shaded bands are plus/minus 1 sample SD across mice. Gaps mean fewer than two valid trials.",
        )
        _append_bin_axes(
            parts,
            left,
            top,
            chart_width,
            chart_height,
            x,
            y,
            lower,
            upper,
            "Trial-to-trial paw-distance SD (cm)",
            height,
        )
        _append_summary_bands(parts, groups, x, y, lower, upper)
        for mouse in mice:
            color = _condition_color(mouse.condition)
            tooltip = html.escape(
                f"{mouse.condition.title()} | Cage {mouse.cage} Mouse {mouse.animal} | Trial-to-trial paw-distance SD"
            )
            _append_hover_lines(
                parts,
                _line_segments(mouse.standard_deviations, x, y),
                color,
                tooltip,
                2.0,
                0.38,
            )
        _append_summary_lines(parts, groups, x, y)
        _append_group_legend(parts, groups, left + chart_width + 40, top)
        parts.append("</svg>")
        return "\n".join(parts)

    @staticmethod
    def _daily_within_trial_variation_svg(
        dataset: str,
        day: str,
        trial_variations: Iterable[TrialPawDistanceWithinTrialVariation],
        mouse_series: Iterable[MousePawDistanceSeries],
        group_summaries: Iterable[GroupPawDistanceSummary],
    ) -> str:
        """Show position-controlled raw-frame variation for every individual run."""
        del mouse_series  # Group summaries already use equal-mouse weighting.
        trials = sorted(trial_variations, key=_trial_sort_key)
        groups = sorted(group_summaries, key=lambda item: _condition_order(item.condition))
        values = [
            value
            for trial in trials
            for value in trial.standard_deviations
            if _valid(value)
        ]
        values.extend(_summary_edges(groups))
        lower, upper = _zoomed_nonnegative_axis_bounds(values)
        width, height = 1420, 790
        left, right, top, bottom = 96, 390, 94, 150
        chart_width, chart_height = width - left - right, height - top - bottom
        x = _bin_x(left, chart_width)
        y = _value_y(top, chart_height, lower, upper)

        parts = _svg_header(
            width,
            height,
            left,
            f"Back/front paw-distance within-trial variation - {dataset} {day}",
            "Thin lines are individual trials: each point is the sample SD across raw valid frame distances within that 10 cm back-paw bin. Lower SD means less within-run variation.",
            "For group values, each mouse first contributes its average valid trial SD in each bin. Thick lines are group means; shaded bands are plus/minus 1 sample SD across mice.",
        )
        _append_bin_axes(
            parts,
            left,
            top,
            chart_width,
            chart_height,
            x,
            y,
            lower,
            upper,
            "Within-trial back/front paw-distance SD (cm)",
            height,
        )
        _append_summary_bands(parts, groups, x, y, lower, upper)
        for trial in trials:
            color = _condition_color(trial.condition)
            tooltip = html.escape(
                f"{trial.condition.title()} | Cage {trial.cage} Mouse {trial.animal} | "
                f"Trial T{trial.trial} | Raw-frame distance SD by 10 cm bin"
            )
            _append_hover_lines(
                parts,
                _line_segments(trial.standard_deviations, x, y),
                color,
                tooltip,
                1.7,
                0.28,
            )
        _append_summary_lines(parts, groups, x, y)
        _append_group_legend(parts, groups, left + chart_width + 40, top)
        parts.append("</svg>")
        return "\n".join(parts)

    @staticmethod
    def _day_svg(
        dataset: str,
        summaries: Iterable[DayGroupPawDistanceSummary],
        *,
        title: str,
        calculation_note: str,
        comparison_note: str,
        empty_note: str,
        y_label: str,
    ) -> str:
        groups = sorted(summaries, key=lambda item: _condition_order(item.condition))
        days = sorted(
            {day for group in groups for day in group.means},
            key=natural_day_key,
        )
        values: list[float] = []
        for group in groups:
            for day, mean in group.means.items():
                values.append(mean)
                error = group.standard_deviations.get(day)
                if _valid(error):
                    values.extend((mean - float(error), mean + float(error)))
        lower, upper = _zoomed_nonnegative_axis_bounds(values)
        width, height = 1320, 720
        left, right, top, bottom = 96, 330, 94, 126
        chart_width, chart_height = width - left - right, height - top - bottom

        def x(day: str) -> float:
            if len(days) <= 1:
                return left + (chart_width / 2)
            return left + chart_width * days.index(day) / (len(days) - 1)

        y = _value_y(top, chart_height, lower, upper)
        parts = _svg_header(width, height, left, f"{title} - {dataset}", calculation_note, comparison_note)
        if not days:
            parts.append(
                f'<text x="{left}" y="{top + 50}" font-family="Arial" font-size="16" fill="#444">{html.escape(empty_note)}</text>'
            )
            parts.append("</svg>")
            return "\n".join(parts)

        for day in days:
            px = x(day)
            parts.extend(
                (
                    f'<line x1="{px:.1f}" y1="{top}" x2="{px:.1f}" y2="{top + chart_height}" stroke="#e6e6e6"/>',
                    f'<text x="{px:.1f}" y="{top + chart_height + 25}" text-anchor="middle" font-family="Arial" font-size="12">{html.escape(day)}</text>',
                )
            )
        for tick in _axis_ticks(lower, upper):
            py = y(tick)
            parts.extend(
                (
                    f'<line x1="{left}" y1="{py:.1f}" x2="{left + chart_width}" y2="{py:.1f}" stroke="#e6e6e6"/>',
                    f'<text x="{left - 10}" y="{py + 4:.1f}" text-anchor="end" font-family="Arial" font-size="12">{_tick_label(tick)}</text>',
                )
            )
        for group in groups:
            color = _condition_color(group.condition)
            for segment in _day_band_segments(group, days, x, y, lower, upper):
                parts.append(
                    f'<polygon points="{" ".join(segment)}" fill="{color}" fill-opacity="0.18" stroke="none"/>'
                )
        for group in groups:
            color = _condition_color(group.condition)
            for segment in _day_line_segments(group, days, x, y):
                parts.append(
                    f'<polyline points="{" ".join(segment)}" fill="none" stroke="{color}" stroke-width="4" stroke-linecap="round"/>'
                )
            for day, mean in group.means.items():
                parts.append(f'<circle cx="{x(day):.1f}" cy="{y(mean):.1f}" r="4.5" fill="{color}"/>')
        _append_day_legend(parts, groups, left + chart_width + 40, top)
        parts.extend(
            (
                f'<text x="{left + chart_width / 2:.1f}" y="{height - 34}" text-anchor="middle" font-family="Arial" font-size="15">Experimental day</text>',
                f'<text x="25" y="{top + chart_height / 2:.1f}" text-anchor="middle" font-family="Arial" font-size="15" transform="rotate(-90 25 {top + chart_height / 2:.1f})">{html.escape(y_label)}</text>',
                "</svg>",
            )
        )
        return "\n".join(parts)

    @staticmethod
    def _day_bar_svg(
        dataset: str,
        summaries: Iterable[DayGroupPawDistanceSummary],
        *,
        title: str,
        calculation_note: str,
        comparison_note: str,
        empty_note: str,
        y_label: str,
    ) -> str:
        """Render equal-mouse SHAM/STROKE day summaries as paired mean bars.

        Neutral-gray sample-SD ranges sit behind the colored bar, while the
        dark whisker is rendered afterwards so both the upper and lower SD
        endpoints remain visible against the colored fill.
        """
        groups = sorted(summaries, key=lambda item: _condition_order(item.condition))
        days = sorted(
            {day for group in groups for day in group.means},
            key=natural_day_key,
        )
        values: list[float] = []
        for group in groups:
            for day, mean in group.means.items():
                values.append(mean)
                error = group.standard_deviations.get(day)
                if _valid(error):
                    values.extend((mean - float(error), mean + float(error)))
        # A bar chart has a real zero baseline; the normal line-chart helper
        # deliberately zooms away from zero for readability.
        _, upper = _zoomed_nonnegative_axis_bounds(values)
        lower = 0.0
        width, height = 1420, 760
        left, right, top, bottom = 96, 360, 94, 136
        chart_width, chart_height = width - left - right, height - top - bottom
        y = _value_y(top, chart_height, lower, upper)
        baseline_y = y(0.0)

        parts = _svg_header(
            width,
            height,
            left,
            f"{title} - {dataset}",
            calculation_note,
            comparison_note,
        )
        if not days or not groups:
            parts.append(
                f'<text x="{left}" y="{top + 50}" font-family="Arial" font-size="16" fill="#444">{html.escape(empty_note)}</text>'
            )
            parts.append("</svg>")
            return "\n".join(parts)

        for tick in _axis_ticks(lower, upper):
            py = y(tick)
            parts.extend(
                (
                    f'<line x1="{left}" y1="{py:.1f}" x2="{left + chart_width}" y2="{py:.1f}" stroke="#e6e6e6"/>',
                    f'<text x="{left - 10}" y="{py + 4:.1f}" text-anchor="end" font-family="Arial" font-size="12">{_tick_label(tick)}</text>',
                )
            )

        day_spacing = chart_width / len(days)
        group_count = len(groups)
        bar_width = min(64.0, day_spacing * 0.28 / max(group_count, 1))
        bar_gap = min(16.0, bar_width * 0.28)
        group_span = group_count * bar_width + max(group_count - 1, 0) * bar_gap
        for day_index, day in enumerate(days):
            center_x = left + day_spacing * (day_index + 0.5)
            parts.extend(
                (
                    f'<line x1="{center_x:.1f}" y1="{top}" x2="{center_x:.1f}" y2="{top + chart_height}" stroke="#f0f0f0"/>',
                    f'<text x="{center_x:.1f}" y="{top + chart_height + 26}" text-anchor="middle" font-family="Arial" font-size="13">{html.escape(day)}</text>',
                )
            )
            for group_index, group in enumerate(groups):
                mean = group.means.get(day)
                if not _valid(mean):
                    continue
                mean = float(mean)
                color = _condition_color(group.condition)
                offset = -group_span / 2 + bar_width / 2 + group_index * (bar_width + bar_gap)
                bar_center = center_x + offset
                bar_left = bar_center - bar_width / 2
                error = group.standard_deviations.get(day)
                error_top = mean
                error_bottom = mean
                upper_y: float | None = None
                lower_y: float | None = None
                if _valid(error):
                    error_top = min(upper, mean + float(error))
                    error_bottom = max(lower, mean - float(error))
                    upper_y = y(error_top)
                    lower_y = y(error_bottom)
                    parts.append(
                        f'<rect x="{bar_left:.1f}" y="{upper_y:.1f}" width="{bar_width:.1f}" height="{max(0.0, lower_y - upper_y):.1f}" fill="{ERROR_RANGE_COLOR}" fill-opacity="0.24" stroke="none"/>'
                    )

                mean_y = y(mean)
                bar_y = min(mean_y, baseline_y)
                bar_height = abs(baseline_y - mean_y)
                count = group.mouse_counts.get(day, 0)
                if _valid(error):
                    tooltip = (
                        f"{group.condition.title()} | {day}: mean {mean:.3f} cm, "
                        f"SD {float(error):.3f} cm, n={count} mice"
                    )
                else:
                    tooltip = (
                        f"{group.condition.title()} | {day}: mean {mean:.3f} cm, "
                        f"SD unavailable, n={count} mice"
                    )
                parts.append(
                    f'<rect x="{bar_left:.1f}" y="{bar_y:.1f}" width="{bar_width:.1f}" height="{bar_height:.1f}" fill="{color}" cursor="help"><title>{html.escape(tooltip)}</title></rect>'
                )
                if upper_y is not None and lower_y is not None:
                    parts.extend(
                        (
                            f'<line x1="{bar_center:.1f}" y1="{upper_y:.1f}" x2="{bar_center:.1f}" y2="{lower_y:.1f}" stroke="{ERROR_WHISKER_COLOR}" stroke-width="1.75"/>',
                            f'<line x1="{bar_center - 7:.1f}" y1="{upper_y:.1f}" x2="{bar_center + 7:.1f}" y2="{upper_y:.1f}" stroke="{ERROR_WHISKER_COLOR}" stroke-width="1.75"/>',
                            f'<line x1="{bar_center - 7:.1f}" y1="{lower_y:.1f}" x2="{bar_center + 7:.1f}" y2="{lower_y:.1f}" stroke="{ERROR_WHISKER_COLOR}" stroke-width="1.75"/>',
                        )
                    )
                label_y = max(top + 14, y(error_top) - 8)
                parts.append(
                    f'<text x="{bar_center:.1f}" y="{label_y:.1f}" text-anchor="middle" font-family="Arial" font-size="11" font-weight="bold" fill="{ERROR_WHISKER_COLOR}">{mean:.3f} cm</text>'
                )

        _append_day_bar_legend(parts, groups, left + chart_width + 42, top)
        parts.extend(
            (
                f'<text x="{left + chart_width / 2:.1f}" y="{height - 34}" text-anchor="middle" font-family="Arial" font-size="15">Experimental day</text>',
                f'<text x="25" y="{top + chart_height / 2:.1f}" text-anchor="middle" font-family="Arial" font-size="15" transform="rotate(-90 25 {top + chart_height / 2:.1f})">{html.escape(y_label)}</text>',
                "</svg>",
            )
        )
        return "\n".join(parts)


def summarize_group_back_front_paw_distances(
    trial_series: Iterable[TrialPawDistanceSeries],
) -> tuple[list[MousePawDistanceSeries], list[GroupPawDistanceSummary]]:
    """Average trials within each mouse before computing group statistics."""
    by_mouse: dict[tuple[str, str, str, str], list[TrialPawDistanceSeries]] = defaultdict(list)
    for series in trial_series:
        by_mouse[(series.day, series.cage, series.animal, series.condition.upper())].append(series)

    mice: list[MousePawDistanceSeries] = []
    for (day, cage, animal, condition), trials in by_mouse.items():
        mice.append(
            MousePawDistanceSeries(
                day=day,
                cage=cage,
                animal=animal,
                condition=condition,
                bin_means=tuple(
                    statistics.fmean(values)
                    if (
                        values := [
                            trial.bin_means[index]
                            for trial in trials
                            if _valid(trial.bin_means[index])
                        ]
                    )
                    else None
                    for index in range(len(BIN_STARTS_CM))
                ),
            )
        )
    return mice, _group_summaries(mice, lambda item: item.bin_means)


def summarize_back_front_paw_distance_within_trial_variation(
    trial_series: Iterable[TrialPawDistanceSeries],
) -> tuple[
    list[TrialPawDistanceWithinTrialVariation],
    list[MousePawDistanceSeries],
    list[GroupPawDistanceSummary],
]:
    """Summarize position-controlled frame-level stance-distance variation.

    A point in an individual-trial profile is the sample SD of raw frame
    distances *within one 10 cm back-paw bin*.  Consequently, normal changes
    in stance as the mouse advances along the beam do not inflate the metric.
    Each mouse's valid trial SDs are averaged before it enters a group summary.
    """
    trial_variations: list[TrialPawDistanceWithinTrialVariation] = []
    for series in trial_series:
        raw_bins = series.frame_distances_by_bin
        valid_raw_bins = tuple(
            tuple(
                float(value)
                for value in raw_bins[index]
                if _valid(value)
            )
            if index < len(raw_bins)
            else ()
            for index in range(len(BIN_STARTS_CM))
        )
        frame_counts = tuple(
            len(valid_raw_bins[index])
            for index in range(len(BIN_STARTS_CM))
        )
        standard_deviations = tuple(
            statistics.stdev(valid_raw_bins[index])
            if len(valid_raw_bins[index]) >= 2
            else None
            for index in range(len(BIN_STARTS_CM))
        )
        if not any(_valid(value) for value in standard_deviations):
            continue
        trial_variations.append(
            TrialPawDistanceWithinTrialVariation(
                day=series.day,
                cage=series.cage,
                animal=series.animal,
                condition=series.condition.upper(),
                trial=series.trial,
                standard_deviations=standard_deviations,
                frame_counts=frame_counts,
            )
        )

    summary_inputs = _within_trial_variation_summary_inputs(trial_variations)
    mice, groups = summarize_group_back_front_paw_distances(summary_inputs)
    return trial_variations, mice, groups


def summarize_day_by_day_back_front_paw_distance_within_trial_variation(
    trial_series: Iterable[TrialPawDistanceSeries],
) -> list[DayGroupPawDistanceSummary]:
    """Return equal-mouse day summaries of raw-frame within-trial variation."""
    trial_variations, _, _ = summarize_back_front_paw_distance_within_trial_variation(
        trial_series
    )
    return summarize_day_by_day_back_front_paw_distances(
        _within_trial_variation_summary_inputs(trial_variations)
    )


def summarize_back_front_paw_distance_trial_consistency(
    trial_series: Iterable[TrialPawDistanceSeries],
) -> tuple[list[MousePawDistanceConsistency], list[GroupPawDistanceSummary]]:
    """Calculate each mouse's sample SD across trials in each 10 cm bin."""
    by_mouse: dict[tuple[str, str, str, str], list[TrialPawDistanceSeries]] = defaultdict(list)
    for series in trial_series:
        by_mouse[(series.day, series.cage, series.animal, series.condition.upper())].append(series)

    mice: list[MousePawDistanceConsistency] = []
    for (day, cage, animal, condition), trials in by_mouse.items():
        values_by_bin = [
            [
                trial.bin_means[index]
                for trial in trials
                if _valid(trial.bin_means[index])
            ]
            for index in range(len(BIN_STARTS_CM))
        ]
        mice.append(
            MousePawDistanceConsistency(
                day=day,
                cage=cage,
                animal=animal,
                condition=condition,
                standard_deviations=tuple(
                    statistics.stdev(values) if len(values) >= 2 else None
                    for values in values_by_bin
                ),
                trial_counts=tuple(len(values) for values in values_by_bin),
            )
        )
    return mice, _group_summaries(mice, lambda item: item.standard_deviations)


def summarize_day_by_day_back_front_paw_distances(
    trial_series: Iterable[TrialPawDistanceSeries],
) -> list[DayGroupPawDistanceSummary]:
    """Compare stance distance by day, weighting each mouse equally."""
    mice, _ = summarize_group_back_front_paw_distances(trial_series)
    return _day_summaries((mouse.day, mouse.condition, mouse.bin_means) for mouse in mice)


def summarize_day_by_day_back_front_paw_distance_consistency(
    trial_series: Iterable[TrialPawDistanceSeries],
) -> list[DayGroupPawDistanceSummary]:
    """Compare within-mouse trial variation by day, without changing its SD."""
    mice, _ = summarize_back_front_paw_distance_trial_consistency(trial_series)
    return _day_summaries(
        (mouse.day, mouse.condition, mouse.standard_deviations) for mouse in mice
    )


def _within_trial_variation_summary_inputs(
    trial_variations: Iterable[TrialPawDistanceWithinTrialVariation],
) -> list[TrialPawDistanceSeries]:
    """Adapt per-trial raw-frame SD profiles to the shared equal-mouse tools."""
    return [
        TrialPawDistanceSeries(
            day=series.day,
            cage=series.cage,
            animal=series.animal,
            condition=series.condition,
            trial=series.trial,
            bin_means=series.standard_deviations,
        )
        for series in trial_variations
    ]


def _group_summaries(mice: Iterable, values_for) -> list[GroupPawDistanceSummary]:
    by_group: dict[str, list] = defaultdict(list)
    for mouse in mice:
        by_group[mouse.condition.upper()].append(mouse)
    summaries: list[GroupPawDistanceSummary] = []
    for condition, group_mice in by_group.items():
        means: list[float | None] = []
        errors: list[float | None] = []
        counts: list[int] = []
        for index in range(len(BIN_STARTS_CM)):
            values = [
                values_for(mouse)[index]
                for mouse in group_mice
                if _valid(values_for(mouse)[index])
            ]
            counts.append(len(values))
            means.append(statistics.fmean(values) if values else None)
            errors.append(statistics.stdev(values) if len(values) >= 2 else None)
        summaries.append(
            GroupPawDistanceSummary(
                condition=condition,
                means=tuple(means),
                standard_deviations=tuple(errors),
                mouse_counts=tuple(counts),
            )
        )
    return summaries


def _day_summaries(
    values: Iterable[tuple[str, str, tuple[float | None, ...]]],
) -> list[DayGroupPawDistanceSummary]:
    by_group_day: dict[str, dict[str, list[float]]] = defaultdict(lambda: defaultdict(list))
    for day, condition, series in values:
        normalized_condition = condition.upper()
        if normalized_condition not in {"SHAM", "STROKE"}:
            continue
        valid_values = [float(value) for value in series if _valid(value)]
        if valid_values:
            by_group_day[normalized_condition][day].append(statistics.fmean(valid_values))
    return [
        DayGroupPawDistanceSummary(
            condition=condition,
            means={day: statistics.fmean(items) for day, items in per_day.items() if items},
            standard_deviations={
                day: statistics.stdev(items) if len(items) >= 2 else None
                for day, items in per_day.items()
                if items
            },
            mouse_counts={day: len(items) for day, items in per_day.items() if items},
        )
        for condition, per_day in by_group_day.items()
    ]


def _frame_columns(index: dict[str, int]) -> tuple[dict[int, int], dict[int, int], dict[int, int]]:
    compact: dict[int, int] = {}
    distances: dict[int, int] = {}
    positions: dict[int, int] = {}
    for header, column in index.items():
        if not header.startswith("Frame "):
            continue
        try:
            if header.endswith(" distance (cm)"):
                distances[int(header.removeprefix("Frame ").removesuffix(" distance (cm)"))] = column
            elif header.endswith(" back paw (cm)"):
                positions[int(header.removeprefix("Frame ").removesuffix(" back paw (cm)"))] = column
            else:
                compact[int(header.removeprefix("Frame "))] = column
        except ValueError:
            continue
    return compact, distances, positions


def _frame_measurement(
    values: tuple[object, ...],
    frame: int,
    compact: dict[int, int],
    distances: dict[int, int],
    positions: dict[int, int],
) -> tuple[float | None, float | None]:
    if frame in compact:
        column = compact[frame]
        if column >= len(values) or values[column] is None:
            return None, None
        match = FRAME_CELL_RE.fullmatch(str(values[column]).strip())
        if match is None:
            return None, None
        return float(match.group(1)), float(match.group(2))
    return _cell_float(values, distances.get(frame)), _cell_float(values, positions.get(frame))


def _bin_start(position_cm: float) -> int | None:
    if not math.isfinite(position_cm) or not 0.0 <= position_cm <= 90.0:
        return None
    return min(int(position_cm // 10) * 10, 80)


def _svg_header(width: int, height: int, left: int, title: str, note_one: str, note_two: str) -> list[str]:
    return [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}">',
        '<rect width="100%" height="100%" fill="white"/>',
        f'<text x="{left}" y="32" font-family="Arial" font-size="22" font-weight="bold">{html.escape(title)}</text>',
        f'<text x="{left}" y="56" font-family="Arial" font-size="13" fill="#444">{html.escape(note_one)}</text>',
        f'<text x="{left}" y="76" font-family="Arial" font-size="13" fill="#444">{html.escape(note_two)}</text>',
    ]


def _append_bin_axes(
    parts: list[str],
    left: int,
    top: int,
    chart_width: int,
    chart_height: int,
    x,
    y,
    lower: float,
    upper: float,
    y_label: str,
    height: int,
) -> None:
    for start in BIN_STARTS_CM:
        px = x(start)
        parts.extend(
            (
                f'<line x1="{px:.1f}" y1="{top}" x2="{px:.1f}" y2="{top + chart_height}" stroke="#e6e6e6"/>',
                f'<text x="{px:.1f}" y="{top + chart_height + 25}" text-anchor="middle" font-family="Arial" font-size="12">{start}-{start + 10}</text>',
            )
        )
    for tick in _axis_ticks(lower, upper):
        py = y(tick)
        parts.extend(
            (
                f'<line x1="{left}" y1="{py:.1f}" x2="{left + chart_width}" y2="{py:.1f}" stroke="#e6e6e6"/>',
                f'<text x="{left - 10}" y="{py + 4:.1f}" text-anchor="end" font-family="Arial" font-size="12">{_tick_label(tick)}</text>',
            )
        )
    parts.extend(
        (
            f'<text x="{left + chart_width / 2:.1f}" y="{height - 34}" text-anchor="middle" font-family="Arial" font-size="15">Back-paw beam interval (cm)</text>',
            f'<text x="25" y="{top + chart_height / 2:.1f}" text-anchor="middle" font-family="Arial" font-size="15" transform="rotate(-90 25 {top + chart_height / 2:.1f})">{html.escape(y_label)}</text>',
        )
    )


def _append_summary_bands(
    parts: list[str],
    groups: Iterable[GroupPawDistanceSummary],
    x,
    y,
    lower: float,
    upper: float,
) -> None:
    for summary in groups:
        color = _condition_color(summary.condition)
        for segment in _band_segments(summary, x, y, lower, upper):
            parts.append(
                f'<polygon points="{" ".join(segment)}" fill="{color}" fill-opacity="0.18" stroke="none"/>'
            )


def _append_hover_lines(
    parts: list[str],
    segments: Iterable[list[str]],
    color: str,
    tooltip: str,
    width: float,
    opacity: float,
) -> None:
    for points in segments:
        joined = " ".join(points)
        parts.append(
            f'<polyline points="{joined}" fill="none" stroke="{color}" stroke-width="{width}" stroke-opacity="{opacity}" pointer-events="none"/>'
            f'<polyline points="{joined}" fill="none" stroke="{color}" stroke-width="8" stroke-opacity="0" pointer-events="stroke" cursor="help"><title>{tooltip}</title></polyline>'
        )


def _append_summary_lines(
    parts: list[str],
    groups: Iterable[GroupPawDistanceSummary],
    x,
    y,
) -> None:
    for summary in groups:
        color = _condition_color(summary.condition)
        for segment in _line_segments(summary.means, x, y):
            parts.append(
                f'<polyline points="{" ".join(segment)}" fill="none" stroke="{color}" stroke-width="4" stroke-linecap="round"/>'
            )


def _append_group_legend(
    parts: list[str],
    groups: Iterable[GroupPawDistanceSummary],
    legend_x: float,
    top: int,
) -> None:
    parts.append(
        f'<text x="{legend_x}" y="{top + 4}" font-family="Arial" font-size="15" font-weight="bold">Groups</text>'
    )
    for index, summary in enumerate(groups):
        color = _condition_color(summary.condition)
        text_y = top + 30 + index * 28
        count = max(summary.mouse_counts, default=0)
        parts.extend(
            (
                f'<line x1="{legend_x}" y1="{text_y - 5}" x2="{legend_x + 24}" y2="{text_y - 5}" stroke="{color}" stroke-width="4"/>',
                f'<text x="{legend_x + 33}" y="{text_y}" font-family="Arial" font-size="13">{html.escape(summary.condition.title())} (up to n={count} mice)</text>',
            )
        )


def _append_day_legend(
    parts: list[str],
    groups: Iterable[DayGroupPawDistanceSummary],
    legend_x: float,
    top: int,
) -> None:
    parts.append(
        f'<text x="{legend_x}" y="{top + 4}" font-family="Arial" font-size="15" font-weight="bold">Groups</text>'
    )
    for index, summary in enumerate(groups):
        color = _condition_color(summary.condition)
        text_y = top + 30 + index * 28
        count = max(summary.mouse_counts.values(), default=0)
        parts.extend(
            (
                f'<line x1="{legend_x}" y1="{text_y - 5}" x2="{legend_x + 24}" y2="{text_y - 5}" stroke="{color}" stroke-width="4"/>',
                f'<text x="{legend_x + 33}" y="{text_y}" font-family="Arial" font-size="13">{html.escape(summary.condition.title())} (up to n={count} mice)</text>',
            )
        )


def _append_day_bar_legend(
    parts: list[str],
    groups: Iterable[DayGroupPawDistanceSummary],
    legend_x: float,
    top: int,
) -> None:
    """Use colored bar swatches rather than line glyphs for day bar charts."""
    parts.append(
        f'<text x="{legend_x}" y="{top + 4}" font-family="Arial" font-size="15" font-weight="bold">Groups</text>'
    )
    for index, summary in enumerate(groups):
        color = _condition_color(summary.condition)
        text_y = top + 32 + index * 30
        count = max(summary.mouse_counts.values(), default=0)
        parts.extend(
            (
                f'<rect x="{legend_x}" y="{text_y - 12}" width="18" height="12" fill="{color}"/>',
                f'<text x="{legend_x + 28}" y="{text_y}" font-family="Arial" font-size="13">{html.escape(summary.condition.title())} (up to n={count} mice)</text>',
            )
        )


def _line_segments(values: Iterable[float | None], x, y) -> list[list[str]]:
    segments: list[list[str]] = []
    segment: list[str] = []
    for start, value in zip(BIN_STARTS_CM, values):
        if not _valid(value):
            if segment:
                segments.append(segment)
                segment = []
            continue
        segment.append(f"{x(start):.1f},{y(float(value)):.1f}")
    if segment:
        segments.append(segment)
    return segments


def _band_segments(
    summary: GroupPawDistanceSummary,
    x,
    y,
    lower: float,
    upper: float,
) -> list[list[str]]:
    segments: list[list[tuple[float, float, float]]] = []
    segment: list[tuple[float, float, float]] = []
    for start, mean, error in zip(BIN_STARTS_CM, summary.means, summary.standard_deviations):
        if not _valid(mean) or not _valid(error):
            if segment:
                segments.append(segment)
                segment = []
            continue
        segment.append((x(start), float(mean), float(error)))
    if segment:
        segments.append(segment)
    return [
        [
            *(f"{px:.1f},{y(min(upper, mean + error)):.1f}" for px, mean, error in segment),
            *(f"{px:.1f},{y(max(lower, mean - error)):.1f}" for px, mean, error in reversed(segment)),
        ]
        for segment in segments
    ]


def _day_line_segments(
    summary: DayGroupPawDistanceSummary,
    days: Iterable[str],
    x,
    y,
) -> list[list[str]]:
    segments: list[list[str]] = []
    segment: list[str] = []
    for day in days:
        value = summary.means.get(day)
        if not _valid(value):
            if segment:
                segments.append(segment)
                segment = []
            continue
        segment.append(f"{x(day):.1f},{y(float(value)):.1f}")
    if segment:
        segments.append(segment)
    return segments


def _day_band_segments(
    summary: DayGroupPawDistanceSummary,
    days: Iterable[str],
    x,
    y,
    lower: float,
    upper: float,
) -> list[list[str]]:
    segments: list[list[tuple[float, float, float]]] = []
    segment: list[tuple[float, float, float]] = []
    for day in days:
        mean = summary.means.get(day)
        error = summary.standard_deviations.get(day)
        if not _valid(mean) or not _valid(error):
            if segment:
                segments.append(segment)
                segment = []
            continue
        segment.append((x(day), float(mean), float(error)))
    if segment:
        segments.append(segment)

    polygons: list[list[str]] = []
    for segment in segments:
        if len(segment) == 1:
            px, mean, error = segment[0]
            half_width = 10.0
            upper_y = y(min(upper, mean + error))
            lower_y = y(max(lower, mean - error))
            polygons.append(
                [
                    f"{px - half_width:.1f},{upper_y:.1f}",
                    f"{px + half_width:.1f},{upper_y:.1f}",
                    f"{px + half_width:.1f},{lower_y:.1f}",
                    f"{px - half_width:.1f},{lower_y:.1f}",
                ]
            )
            continue
        polygons.append(
            [
                *(f"{px:.1f},{y(min(upper, mean + error)):.1f}" for px, mean, error in segment),
                *(f"{px:.1f},{y(max(lower, mean - error)):.1f}" for px, mean, error in reversed(segment)),
            ]
        )
    return polygons


def _bin_x(left: int, chart_width: int):
    return lambda start: left + chart_width * (start + 5) / 90


def _value_y(top: int, chart_height: int, lower: float, upper: float):
    return lambda value: top + chart_height * (upper - value) / (upper - lower)


def _zoomed_nonnegative_axis_bounds(values: Iterable[float]) -> tuple[float, float]:
    """Return a readable tight axis without clipping data or SD ribbons.

    Back/front-paw distance is a continuous line measurement, not a bar chart,
    so a forced zero baseline only obscures meaningful between-group changes.
    The caller supplies all plotted observations plus mean +/- SD edges; this
    helper rounds a small data-driven margin to readable tick values.  Negative
    values remain excluded because this metric and its sample SD are
    nonnegative.
    """
    finite_values = [float(value) for value in values if math.isfinite(float(value))]
    if not finite_values:
        return 0.0, 1.0

    minimum = max(0.0, min(finite_values))
    maximum = max(finite_values)
    span = maximum - minimum
    padding = max(0.02, span * 0.02) if span > 1e-9 else max(0.5, maximum * 0.15)
    lower_value = max(0.0, minimum - padding)
    upper_value = maximum + padding

    # Keep enough vertical room to distinguish nearly identical values while
    # avoiding an overstated chart when every value is identical.
    if upper_value - lower_value < 0.5:
        center = (upper_value + lower_value) / 2.0
        lower_value = max(0.0, center - 0.25)
        upper_value = center + 0.25

    step = _nice_axis_step((upper_value - lower_value) / 6.0)
    lower = max(0.0, math.floor(lower_value / step) * step)
    upper = math.ceil(upper_value / step) * step
    if upper - lower < step * 2:
        upper = lower + (step * 2)
    return lower, upper


def _nice_axis_step(target: float) -> float:
    """Return a 1/2/5-style step near one sixth of the rendered range."""
    if target <= 0 or not math.isfinite(target):
        return 1.0
    magnitude = 10 ** math.floor(math.log10(target))
    normalized = target / magnitude
    for candidate in (1.0, 2.0, 5.0, 10.0):
        if normalized <= candidate:
            return candidate * magnitude
    return 10.0 * magnitude


def _axis_ticks(lower: float, upper: float) -> list[float]:
    step = _nice_axis_step((upper - lower) / 6.0)
    count = max(1, int(round((upper - lower) / step)))
    return [round(lower + (index * step), 10) for index in range(count + 1)]


def _tick_label(value: float) -> str:
    return str(int(value)) if value.is_integer() else f"{value:.1f}"


def _all_bin_values(series: Iterable[TrialPawDistanceSeries]) -> list[float]:
    return [float(value) for item in series for value in item.bin_means if _valid(value)]


def _summary_edges(groups: Iterable[GroupPawDistanceSummary]) -> list[float]:
    values: list[float] = []
    for group in groups:
        for mean, error in zip(group.means, group.standard_deviations):
            if not _valid(mean):
                continue
            values.append(float(mean))
            if _valid(error):
                values.extend((float(mean) - float(error), float(mean) + float(error)))
    return values


def _valid(value: float | None) -> bool:
    return value is not None and math.isfinite(float(value))


def _cell_text(values: tuple[object, ...], index: int | None) -> str:
    if index is None or index >= len(values) or values[index] is None:
        return ""
    value = values[index]
    return str(int(value)) if isinstance(value, float) and value.is_integer() else str(value).strip()


def _cell_float(values: tuple[object, ...], index: int | None) -> float | None:
    if index is None or index >= len(values) or values[index] is None:
        return None
    try:
        value = float(values[index])
    except (TypeError, ValueError):
        return None
    return value if math.isfinite(value) else None


def _cell_int(values: tuple[object, ...], index: int | None) -> int:
    value = _cell_float(values, index)
    return int(value) if value is not None else 0


def _condition_color(condition: str) -> str:
    return {
        "SHAM": SHAM_COLOR,
        "STROKE": STROKE_COLOR,
    }.get(condition.upper(), UNASSIGNED_COLOR)


def _condition_order(condition: str) -> tuple[int, str]:
    normalized = condition.upper()
    return ({"SHAM": 0, "STROKE": 1}.get(normalized, 2), normalized)


def _numeric_key(value: str) -> tuple[int, int | str]:
    return (0, int(value)) if value.isdigit() else (1, value.casefold())


def _trial_sort_key(series: TrialPawDistanceSeries):
    return (
        _condition_order(series.condition),
        _numeric_key(series.cage),
        _numeric_key(series.animal),
        series.trial,
    )
